# Task: Configuration for generating 5000 samples using the cifar10 dataset
num_samples: 5000
batch_size: 64
M: 20
dropout: 0.0
multi_gpu: true
scheduler_type: uncertainty_centered
start_step_uc: 0
num_steps_uc: 50
generation_steps: 50
start_index: 10_000
model_type: unet
seed: 4918983
predict_next: false
eta: 0.0
image_size: 32