# runs with generation steps 50 on imagenet64 
percentile: 0.85
start_step_threshold: 0
num_steps_threshold: 20
dataset_name: imagenet64
num_samples: 10_000
batch_size: 128
on_cpu: false
seed: 853983298
scheduler_type: uncertainty_centered
start_step_guidance: 15
num_steps_guidance: 3
use_percentile: true
num_steps: 20
guidance_type: posterior